# Generated by Django 3.2.3 on 2021-05-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mudrosty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_blog', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('description_blog', models.TextField(null=True, verbose_name='Фраза')),
                ('name_blogers', models.TextField(verbose_name='Имя блогера')),
            ],
        ),
    ]
